### ISSUE TITLE
ERROR: You must provide the Tumor BAM files to the option --lbams ; Aborting.

### ISSUE THREAD

**Issue by awchrist** [tgen/vcfMerger2#13]
I am getting the following error, however there is no option "--lbams" based on the options list.
ERROR: You must provide the Tumor BAM files to the option --lbams ; Aborting.

**Comment by awchrist** [comment]
When it fails this check it is also not exiting with a non zero exit status.

**Comment by ChristopheLegendre** [comment]
- forgot to add the number `1` into the exit status code when an error is raised; --> FIXED  

- `--lbams`  was a typo in the error message ; `--bams` is correct as you figured.  --> FIXED

- Added testing the value of the variable `skip-prep-vcfs` when strelka2 tool is provided; --FIXED line 844 and 846 in vcfMErger2 code version 0.7.6  ; creation of release 0.7.7
