### ISSUE TITLE
Octopus AR precision

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/vcfMerger2#16]
https://github.com/tgen/vcfMerger2/blob/20676d9cd31e53a90462599a2c3b5cb87681d0be/prep_vcfs_somatic/octopus/octopus.somatic.addFieldsForVcfMerger.py#L398-L410

I would round to 3rd or 4th precision, right now a 2/44 = 0.04545 becomes 0.05 and then gets into merged vcf after filtering AR >= 0.05.  But in this example it didn't meet the actual threshold but did because we rounded up to the 2nd precision level

**Comment by ChristopheLegendre** [comment]
Each AR value is now rounded with 4 digits precision.
