### ISSUE TITLE
vcfMerger could use Pisces module

### ISSUE THREAD

**Issue by sfacista** [tgen/vcfMerger2#21]
We are using http://uswest.ensembl.org/Canis_familiaris/Info/Index for a reference genome. Unfortunately, all we have left is normalized VCF. I have to go back in a re-run to generate raw VCF's. All I have left right now is the compressed/ normalized VCF's. I will attach it as soon as I acquire it.

**Comment by ChristopheLegendre** [comment]
@sfacista 
Hi Sal,
What is the issue you are trying to describe?
Could you be more specific regarding the error you got while running vcfMerger2 for canine?

**Comment by PedalheadPHX** [comment]
The request is to develop a prep script for PICES (https://github.com/Illumina/Pisces) vcf files, I ask Sal to provide some examples

**Comment by ChristopheLegendre** [comment]
Sorry for the confusion: I thought `Pisces` was the name of an organism; In latin, `Pisces` means "fish" or thought it could be related to canine ; I did not think about a toolname.

**Comment by ChristopheLegendre** [comment]
'won't implement'

This won't be implemented as of today; 
If example of `Pisces`  somatic VCFs are provided and `Pisces` appears to be an accurate and fast somatic variant caller after the submitter of the issue or anyone else has shown us comparisons with other callers, please feel free to re-open the issue.
Thanks.
Best.
C.
