### ISSUE TITLE
typo or wrong annotation

### ISSUE THREAD

**Issue by ChristopheLegendre** [tgen/vcfMerger2#26]
https://github.com/tgen/vcfMerger2/blob/8ed9a05b7a23c8a0c2db80fcf83683c35f6602a7/prep_vcfs_somatic/strelka2/strelka2.phasing_consecutives_variants_as_blocs.sh#L137

replace `homozygous` with `heterozygous` on that line.

**Comment by PedalheadPHX** [comment]
Doesn't ALT-ALT = Homozygous ALT

**Comment by ChristopheLegendre** [comment]
The issue was not really with this line but the check_ev line 139 which was a copy/paste of a previous statement. 
That misleading. 
modification will be applied accordingly.
