### ISSUE TITLE
sorting contigs same way in header and data

### ISSUE THREAD

**Issue by ChristopheLegendre** [tgen/vcfMerger2#8]
The contigs must be ordered the same way in the header of the merged vcf and in the data section.

**Comment by ChristopheLegendre** [comment]
@ChristopheLegendre @PedalheadPHX @ryanrichholt 
This issue was **resolved** by adding the same type of sorting to the contigs as it was for the variant.  
the following line got updated:
`https://github.com/tgen/vcfMerger2/blob/abaa4af5d568f8ffafa1eb857e260d931df64776/merge_vcfs/dvmfuncs.py#L125`

**Comment by PedalheadPHX** [comment]
Have you confirmed the final order is correct, find it hard to believe any sort function will do it correctly as some are manually assigned to order sets

chromosome
mapped contig
unknown contig
known decoy
random decoy
EBV
HLA

**Comment by ChristopheLegendre** [comment]
@PedalheadPHX 
Jonathan, 
- OK; I misunderstood a little; I thought you wanted the same order between the contigs in header and the contigs in data section;  
- Actually, you wanted the order of the contigs `in the header` based exactly on the order found in the  fasta reference genome dictionary file (`genome.dict` like file) 

@ryanrichholt 
#### Fix?
The vcfMerger2.py takes another option `--dict` to provide the sequence dictionary file; 
The order of the contigs in the merged vcf's header is **now** ordered based on that dictionary.
With this fix, the variants are still ordered alphanumerically in a natural order way, and therefore, we still can run bcftools sort on the merged vcf file.   If the order of the variant needs to be in the same order as in the reference genome dictionary, we can enable it easily.
