### ISSUE TITLE
Wrong Terminology

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/vcfMerger2#9]
--dict to provide .fai file

The .fai is a TABIX index, there is a .dict file, these are two different things.  We should use the correct term so if you expect a .fai file as input the variable should be --tabix_index

**Comment by ChristopheLegendre** [comment]
I modified the terminology in the release ; 
I meant `.dict` all the time but written `.fai`.
So the file to provide is a `.dict` file created by `picard` tool.

'`--dict`' added to the wiki page ` 'OptionsAndArguments' `.
